Revert "REFPLTB-1070: Integrate and compile Opensync_2.0 recipe for RPI4 target"
This reverts commit 8e93c02f890e13bc3fa0c2ac15db0ab729d8a2ed.

Reason for revert: This is causing build failures:
| make[1]: *** No rule to make target 'client_wifi_hal.c', needed by 'libhal_wifi_la-client_wifi_hal.lo'.  Stop.
| make[1]: *** Waiting for unfinished jobs....

plus
| ../git/source/wifi/client_wifi_hal.c:9:16: fatal error: ev.h: No such file or directory
|  #include <ev.h>
|                 ^

Change-Id: Iddc9752878196fe761db417db74bb47b8a7fa26c