Revert "REFPLTB-151 : Device.DHCPv4.Client.1.IPRouters returns empty value"
This is causing build failues:
"
| ../git/source/dhcpv4c/dhcpv4c_api.c:347:15: error: 'buf' undeclared (first use in this function)
|          fgets(buf,sizeof(buf),fr);
|                ^
"
This reverts commit 1d536dd5eec6f93a596e31a6330fe47205732842.

Change-Id: I9b19b6d659c3f178da8602586527526a48fc475f